### ISSUE TITLE
Broken prune output parsing with Restic 0.13.0

### ISSUE THREAD

**Issue by NilsGriebner** [sinnwerkstatt/runrestic#51]
Just updated to Restic 0.13.0 and faced a traceback in the prune stage, which is likely caused by changed output

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/runrestic/restic/runner.py", line 204, in prune
    process_infos
  File "/usr/local/lib/python3.7/dist-packages/runrestic/restic/output_parsing.py", line 64, in parse_prune
    )[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/runrestic", line 10, in <module>
    sys.exit(runrestic())
  File "/usr/local/lib/python3.7/dist-packages/runrestic/runrestic/runrestic.py", line 75, in runrestic
    runner.run()
  File "/usr/local/lib/python3.7/dist-packages/runrestic/restic/runner.py", line 57, in run
    self.prune()
  File "/usr/local/lib/python3.7/dist-packages/runrestic/restic/runner.py", line 210, in prune
    ] = parse_new_prune(process_infos)
  File "/usr/local/lib/python3.7/dist-packages/runrestic/restic/output_parsing.py", line 105, in parse_new_prune
    )[0]
IndexError: list index out of range
```

**Comment by andreasnuesslein** [comment]
Hey @NilsGriebner thanks for the bug report.

I'm pretty swamped. Would you be able to create a PR?

**Comment by NilsGriebner** [comment]
Yep, I'll look into it when I find a minute :)

**Comment by palto42** [comment]
The issue is a missing ":" after "this removes": https://github.com/sinnwerkstatt/runrestic/blob/d18648ee01a88d149573f735a2bab8c53aaef2da/runrestic/restic/output_parsing.py#L104

In [my fork](https://github.com/palto42/runrestic/tree/palto_dev) this is fixed together with a few other fixes and improvements (#46, #47, successful tests on travis), but I'm afraid the changes are to significant for one PR already.

**Comment by andreasnuesslein** [comment]
I think @palto42  fixed this, right? Thanks!

**Comment by gmag11** [comment]
I guess this is broken again after Restic update to 0.14.0

This happens with Restic 0.14.0 and RunRestic 0.5.26.1 from pip.

```
$ restic version
restic 0.14.0 compiled with go1.19 on linux/arm64
$ runrestic -v
runrestic
0.5.26.1
```

```
Traceback (most recent call last):
  File "/usr/local/bin/runrestic", line 8, in <module>
    sys.exit(runrestic())
  File "/usr/local/lib/python3.8/dist-packages/runrestic/runrestic/runrestic.py", line 81, in runrestic
    result.append(runner.run())
  File "/usr/local/lib/python3.8/dist-packages/runrestic/restic/runner.py", line 56, in run
    self.backup()
  File "/usr/local/lib/python3.8/dist-packages/runrestic/restic/runner.py", line 143, in backup
    metrics[redact_password(repo, self.pw_replacement)] = parse_backup(
  File "/usr/local/lib/python3.8/dist-packages/runrestic/restic/output_parsing.py", line 19, in parse_backup
    added_to_the_repo = re.findall(
IndexError: list index out of range
```
