### ISSUE TITLE
Somewhere the return code is still called "rc"

### ISSUE THREAD

**Issue by andreasnuesslein** [sinnwerkstatt/runrestic#62]
Hey @palto42 ,

I think you missed a `rc` somewhere - do you have time to check real quick?

```
Aug 16 02:51:34 bkp1 runrestic[1530969]:       "total_file_count": 250361,
Aug 16 02:51:34 bkp1 runrestic[1530969]:       "total_size_bytes": 1324666550,
Aug 16 02:51:34 bkp1 runrestic[1530969]:       "duration_seconds": 7.828546524047852,
Aug 16 02:51:34 bkp1 runrestic[1530969]:       "rc": 0
Aug 16 02:51:34 bkp1 runrestic[1530969]:     }
Aug 16 02:51:34 bkp1 runrestic[1530969]:   },
Aug 16 02:51:34 bkp1 runrestic[1530969]:   "last_run": 1660611094.014,
Aug 16 02:51:34 bkp1 runrestic[1530969]:   "total_duration_seconds": 56.1098952293396
Aug 16 02:51:34 bkp1 runrestic[1530969]: }
Aug 16 02:51:34 bkp1 runrestic[1530969]: Traceback (most recent call last):
Aug 16 02:51:34 bkp1 runrestic[1530969]:   File "/usr/local/bin/runrestic", line 8, in <module>
Aug 16 02:51:34 bkp1 runrestic[1530969]:     sys.exit(runrestic())
Aug 16 02:51:34 bkp1 runrestic[1530969]:   File "/usr/local/lib/python3.10/dist-packages/runrestic/runrestic/runrestic.py", line 81, in runrestic
Aug 16 02:51:34 bkp1 runrestic[1530969]:     result.append(runner.run())
Aug 16 02:51:34 bkp1 runrestic[1530969]:   File "/usr/local/lib/python3.10/dist-packages/runrestic/restic/runner.py", line 73, in run
Aug 16 02:51:34 bkp1 runrestic[1530969]:     write_metrics(self.metrics, self.config)
Aug 16 02:51:34 bkp1 runrestic[1530969]:   File "/usr/local/lib/python3.10/dist-packages/runrestic/metrics/__init__.py", line 12, in write_metrics
Aug 16 02:51:34 bkp1 runrestic[1530969]:     file.writelines("".join(lines))
Aug 16 02:51:34 bkp1 runrestic[1530969]:   File "/usr/local/lib/python3.10/dist-packages/runrestic/metrics/prometheus.py", line 205, in generate_lines
Aug 16 02:51:34 bkp1 runrestic[1530969]:     yield backup_metrics(metrics["backup"], name)
Aug 16 02:51:34 bkp1 runrestic[1530969]:   File "/usr/local/lib/python3.10/dist-packages/runrestic/metrics/prometheus.py", line 222, in backup_metrics
Aug 16 02:51:34 bkp1 runrestic[1530969]:     retval += _restic_pre_hooks.format(name=name, **mtrx)
Aug 16 02:51:34 bkp1 runrestic[1530969]: KeyError: 'rc'
```

cheers

**Comment by palto42** [comment]
Hi @andreasnuesslein , sorry for that, seems we miss some unit testing for the prometheus module ;-)
Will have a look and hopefully get it fixed quickly.

**Comment by andreasnuesslein** [comment]
thanks a bunch!
